language: node_js

cache: yarn

node_js:
  - 'stable'
  - '6'
  - '8'

sudo: false

script:
  - yarn test

deploy:
  - provider: npm
    email: 'devmonk@mediamonks.com'
    api_key:
      secure: 'K1pQ5f6JHksTeDjnIkqxNDvwFIY3c2606py01EZ8wROCUUsEIlX6GGmip30/xIANT4WVm74i2/bkR+RrlyXzQSVT5CuD8ob/WcC/Ez+C36NIXustrHo3lEQS0K0e3HmQxm/TBHetk9L+vVe4/lQzbQPG2OjVQfn202B5eAOaV4alRn6+9KU1rRBp9ctrVSCa4bu7rPDGnEZstqB8el27LDz5g0WphU6i4LWSeUaoZhCG41G6/ui1dK491M6TcaGpbUQW1eck5gsM6S0iHvB4/jbUOg6V7+334nXylcQ86jDamXyA9fJqB6p2E+/yPs3wTY5emAMbR5W6CT/S9KXrDILWvrXK9a+Cu98yMSf/yUpQedyTNMpB24D4Ch3GqzgrSacYTe3NX/HtygLYJayt/iwz8ZmJZWRZYfkEuiE8va4Ex6+Fv6o27eVGKDowqhKnOaaut0J01DngoV6n6I6AbjjGABJBl4tiKDxUCUcXZl7z1wFZRbKcJB6If7kJD/1n9wvw9RmdIWAGBJyZ/Yp9Z9lybFQ0SArQeFlvYhXjc85o5wDxFaR60ccNDw8OaKbFyB0JmqtJX4fWVVywNutzCGQ4IKPeeNLESrKc9zdnlSbHLMj2rxXUPmEStvB+fR9rZikZXa7DlAMv3jLXt/0+BXHJU5u22rwXKjuX34gjMpM='
    on:
      tags: true
      node: '8'
    skip_cleanup: true
